[package]
name = "croni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17", features = ["full"] }
tokio-cron-scheduler = "0.5"
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
